# obtain the project details
#
# Copyright (C) 2019 RIKEN, Kazusa DNA Research Institute and National Institute of Genetics.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

SELECT DISTINCT ?proj ?speciesLabel ?expTypeLabel ?expFactorLabel ?piName ?piAffiName ?ref ?otherInfo ?desc
WHERE {

  Optional {
    ?proj <http://metadb.riken.jp/ontology/plantMetabolomics/0.1/principalInvestigator> ?pi .
    Optional {
      ?pi <http://www.w3.org/2000/01/rdf-schema#label> ?piName .
      Optional {
        ?pi <http://metadb.riken.jp/ontology/plantMetabolomics/0.1/affiliation> ?piAffi .
        ?piAffi <http://www.w3.org/2000/01/rdf-schema#label> ?piAffiName .
  }}}

  Optional {
    ?proj <http://purl.org/dc/dcmitype/references> ?ref .
  }

  Optional {
    ?proj <http://www.w3.org/2000/01/rdf-schema#seeAlso> ?otherInfo .
  }
  
  Optional {
    ?proj <http://purl.org/dc/dcmitype/description> ?desc .
  }
  
  ?proj <http://metadb.riken.jp/ontology/plantMetabolomics/0.1/experiment> ?exp . 
  Optional {
    ?exp <http://metadb.riken.jp/ontology/plantMetabolomics/0.1/measurement> ?measurement .
    ?measurement <http://metadb.riken.jp/ontology/plantMetabolomics/0.1/sampleMeasured> ?sample .
    ?sample <http://metadb.riken.jp/ontology/plantMetabolomics/0.1/biologicalSample> ?bioSample .
    ?bioSample <http://purl.obolibrary.org/obo/RO_0002162> ?species .
    ?species <http://www.w3.org/2004/02/skos/core#prefLabel> ?speciesLabel .
  }

  ?exp <http://metadb.riken.jp/ontology/plantMetabolomics/0.1/experimentalDesign> ?expDesign .
  Optional {
     ?expDesign <http://metadb.riken.jp/ontology/plantMetabolomics/0.1/experimentType> ?expType .
    ?expType <http://www.w3.org/2000/01/rdf-schema#label> ?expTypeLabel .
  }
  Optional {
    ?expDesign <http://metadb.riken.jp/ontology/plantMetabolomics/0.1/experimentalFactor> ?expFactor .
    ?expFactor <http://www.w3.org/2000/01/rdf-schema#label> ?expFactorLabel .
  }


  FILTER( ?proj = <http://metadb.riken.jp/db/plantMetabolomics/0.1/Project/RPMM0033> ).
}
